create schema Clube_do_livro;

create table LIVROS (
ID_LIVRO INT NOT NULL,
NOME_LIVRO varchar (100) NOT NULL,
AUTORIA VARCHAR (100) NOT NULL,
EDITORA VARCHAR (100) NOT NULL,
CATEGORIA VARCHAR (100) NOT NULL,
PRECO decimal (5,2) NOT NULL,

primary key (ID_LIVRO)
)

CREATE TABLE ESTOQUE (
ID_LIVRO INT NOT NULL,
QTD_ESTOQUE INT NOT NULL,
PRIMARY KEY (ID_LIVRO)
);

create table VENDAS (
ID_PEDIDO INT NOT NULL,
ID_VENDEDOR INT NOT NULL,
ID_LIVRO INT NOT NULL,
QTD_ESTOQUE INT NOT NULL,
DATA_VENDA DATE NOT NULL,
primary key (ID_VENDEDOR, ID_PEDIDO)

);

CREATE table VENDEDORES (
ID_VENDEDOR INT NOT NULL,
NOME_VENDEDOR varchar (100) NOT NULL,
primary key (ID_VENDEDOR)
);
ALTER table ESTOQUE ADD CONSTRAINT CE_ESTOQUE_LIVROS
foreign key (ID_LIVRO)
references LIVRO (ID_LIVRO)

